jwt:
  secret: "THISISJWTSECRETKEYTHISISJWTSECRETKEY"
  expiration: 1800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    try-it-out-enabled: true
    persist-authorization: true

#---
#
#spring:
#  config:
#    activate:
#      on-profile: ty
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    open-in-view: true
#
## logging:
##   level:
##     root: info
#
#---

spring:
  config:
    activate:
      on-profile: dg

  datasource:
    url: jdbc:mysql://192.168.45.133:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ldk
    password: 1q2w3e!Q@W#E
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
  file:
    name: logs/logfile.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/logfile-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  level:
    root: info
    com.zaxxer.hikari: debug
    org.springframework.jdbc: debug
