jwt:
  secret: "THISISJWTSECRETKEYTHISISJWTSECRETKEY"
  expiration: 1800

---

spring:
  config:
    activate:
      on-profile: ty

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

---

spring:
  config:
    activate:
      on-profile: dg

  datasource:
    url: jdbc:mysql://localhost:3308/mydb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
  file:
    name: logs/logfile.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/logfile-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  level:
    root: info