spring:
  datasource:
    url: jdbc:mysql://localhost:3308/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  spring:
    jpa:
      hibernate:
        ddl-auto: none                # 스키마 자동 생성/수정 비활성화
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8용 Hibernate 방언
      database-platform: org.hibernate.dialect.MySQL8Dialect  # 선택적, dialect와 동일
      show-sql: true                 # SQL 쿼리 출력
      properties:
        hibernate:
          format_sql: true           # SQL 포맷팅
      open-in-view: true             # Lazy Loading 지원

jwt:
  secret: "THISISJWTSECRETKEYTHISISJWTSECRETKEY"
  expiration: 1800

# mybatis:
#   mapper-locations: classpath:repositories/*Repository.xml
#   type-aliases-package: com.example.**.model
#   configuration:
#     map-underscore-to-camel-case: true
#     call-setters-on-nulls: true
#     jdbc-type-for-null: varchar

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
  file:
    name: logs/logfile.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/logfile-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  level:
    root: info

#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: Ant_path_matcher
