spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

<<<<<<< HEAD
  spring:
    jpa:
      hibernate:
        ddl-auto: none                # 스키마 자동 생성/수정 비활성화
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8용 Hibernate 방언
      database-platform: org.hibernate.dialect.MySQL8Dialect  # 선택적, dialect와 동일
      show-sql: true                 # SQL 쿼리 출력
      properties:
        hibernate:
          format_sql: true           # SQL 포맷팅
      open-in-view: true             # Lazy Loading 지원
=======
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
>>>>>>> origin/master

jwt:
  secret: "THISISJWTSECRETKEYTHISISJWTSECRETKEY"
  expiration: 1800

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) %magenta(%-4relative) --- [%thread{15}] %cyan(%logger{20}) : %msg%n"
  file:
    name: logs/logfile.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/logfile-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  level:
    root: info

