name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Create JAR file
        run: ./gradlew bootJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: board-application
          path: build/libs/*.jar

      - name: Build info
        run: |
          echo "Build completed successfully!"
          echo "JAR files created:"
          ls -la build/libs/

  # 리눅스 서버 배포
  deploy-linux-server:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: board-application
          path: ./artifacts

      - name: Create deployment directory and copy files
        run: |
          mkdir -p deploy
          cp ./artifacts/*.jar deploy/app.jar
          cp DeployServer.sh deploy/
          chmod +x deploy/DeployServer.sh

      - name: Create deployment package
        run: |
          cd deploy
          tar -czf ../deployment.tar.gz .

      - name: Deploy to Linux Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 192.168.45.133
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "deployment.tar.gz"
          target: "/home/${{ secrets.SERVER_USER }}/"
          strip_components: 0

      - name: Extract and Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.45.133
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # 배포 디렉토리 생성
            mkdir -p ~/board-app
            cd ~/board-app
            
            # 기존 애플리케이션 종료
            if [ -f app.pid ]; then
              PID=$(cat app.pid)
              if ps -p $PID > /dev/null 2>&1; then
                echo "Stopping existing application (PID: $PID)..."
                kill $PID
                sleep 3
                if ps -p $PID > /dev/null 2>&1; then
                  kill -9 $PID
                fi
              fi
              rm -f app.pid
            fi
            
            # 배포 파일 압축 해제
            cd ~
            tar -xzf deployment.tar.gz -C ~/board-app/
            rm deployment.tar.gz
            
            # 실행 권한 부여
            chmod +x ~/board-app/DeployServer.sh
            
            # 애플리케이션 실행
            cd ~/board-app
            ./DeployServer.sh

      - name: Health Check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.45.133
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Checking application status..."
            sleep 10
            
            # 프로세스 확인
            if ps aux | grep -v grep | grep "java.*app.jar" > /dev/null; then
              echo " Application is running"
              
              # 포트 확인
              if netstat -tlnp 2>/dev/null | grep :8080 > /dev/null; then
                echo " Port 8080 is listening"
              else
                echo " Port 8080 is not listening"
              fi
              
              # 로그 확인
              echo "Recent logs:"
              tail -n 10 ~/board-app/app.log || echo "No log file found"
              
            else
              echo " Application is not running"
              echo "Checking logs for errors:"
              tail -n 20 ~/board-app/app.log || echo "No log file found"
              exit 1
            fi




