name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Create JAR file
        run: ./gradlew bootJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: board-application
          path: build/libs/*.jar

      - name: Build info
        run: |
          echo "Build completed successfully!"
          echo "JAR files created:"
          ls -la build/libs/

  # CD: SSH를 통해 로컬 PC의 스크립트 자동 실행
  deploy-local:
    runs-on: ubuntu-latest  # GitHub 서버에서 실행
    needs: build
    if: github.ref == 'refs/heads/master'  # master 브랜치에만 배포

    steps:
      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: board-application
          path: ./artifacts

      - name: Upload JAR to local PC
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USERNAME }}
          key: ${{ secrets.LOCAL_SSH_KEY }}
          port: ${{ secrets.LOCAL_SSH_PORT }}
          source: "./artifacts/*.jar"
          target: "/tmp/artifacts"
          strip_components: 0
          debug: true  # 디버그 모드 추가

      - name: Execute local deployment script
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USERNAME }}
          key: ${{ secrets.LOCAL_SSH_KEY }}
          port: ${{ secrets.LOCAL_SSH_PORT }}
          script: |
            echo "========================================"
            echo "Executing Local Deployment Script"
            echo "========================================"
            echo "Date: $(date)"
            echo "Host: $(hostname)"
            
            # 프로젝트 디렉토리로 이동
            cd "$HOME/Board_JPA-master"
            
            # JAR 파일을 artifacts 폴더로 복사
            mkdir -p artifacts
            cp /tmp/artifacts/*.jar artifacts/
            
            # OS 감지 및 적절한 스크립트 실행
            if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" ]]; then
                echo "Detected: Windows Environment"
                echo "Executing deploy-local.bat..."
                
                # Windows 배치 파일 실행
                if [ -f "deploy-local.bat" ]; then
                    chmod +x deploy-local.bat
                    ./deploy-local.bat
                else
                    echo "ERROR: deploy-local.bat not found!"
                    exit 1
                fi
            else
                echo "Detected: Linux/Unix Environment"
                echo "Executing deploy-server.sh..."
                
                # Linux shell 스크립트 실행
                if [ -f "deploy-server.sh" ]; then
                    chmod +x deploy-server.sh
                    ./deploy-server.sh
                else
                    echo "ERROR: deploy-server.sh not found!"
                    exit 1
                fi
            fi
            
            echo "Local deployment script execution completed!"

  # SSH를 통한 원격 배포 (주석처리)
  # deploy-local-ssh:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/master'
  #
  #   steps:
  #     - name: Download JAR artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: board-application
  #         path: ./artifacts
  #
  #     - name: Deploy to local PC via SSH
  #       uses: appleboy/ssh-action@v0.1.5
  #       with:
  #         host: ${{ secrets.LOCAL_HOST }}
  #         username: ${{ secrets.LOCAL_USERNAME }}
  #         key: ${{ secrets.LOCAL_SSH_KEY }}
  #         port: ${{ secrets.LOCAL_SSH_PORT }}
  #         script: |
  #           # SSH 스크립트 내용 (주석처리)
  #
  #     - name: Upload JAR to local PC
  #       uses: appleboy/scp-action@v0.1.4
  #       with:
  #         host: ${{ secrets.LOCAL_HOST }}
  #         username: ${{ secrets.LOCAL_USERNAME }}
  #         key: ${{ secrets.LOCAL_SSH_KEY }}
  #         port: ${{ secrets.LOCAL_SSH_PORT }}
  #         source: "./artifacts/*.jar"
  #         target: "/tmp/artifacts"
  #         strip_components: 0



